# Config files for changing up the plugin!

#sets the name of the worlds
world-names: world

#Sets if chances should of getting undead armor should go up the more someone dies
death-count-affects-undead-chance: true
#Sets the increment of said chance above
death-count-increment: 0.2
#sets the cooldown for deaths to avoid abuse (in seconds)
death-count-cooldown: 60

#----------Loot----------
loot-spawn-in-dungeons: true
loot-spawn-in-shipwreck: true
loot-spawn-in-villages: true
loot-spawn-in-mineshaft: true
loot-spawn-in-buried-treasure: true
loot-spawn-in-igloo: true

#----------Blood Moons-----------------
#Sets the increment of blood moons (how much per night the chance will increase)
blood-moon-increment: 1
#Should mobs spawn with some potion effects (Strength, regen)?
mobs-spawn-powerful-blood: true
strength-level-blood: 2
regen-level-blood: 1
#in half-hearts
health-level-blood: 20
#set if mobs should drop items, if so, what chance.
mobs-drop-items-blood: false
mobs-drop-items-chance-blood: 3

#----------Blue Moons------------------
#Sets the increment of blue moons
blue-moon-increment: 1
#set what potion effects Blue Moons should give. put 0 to disable the potion effect.
strength-level-blue: 1
speed-level-blue: 1
luck-level-blue: 2
resistance-level-blue: 1
#Set if mobs should have a chance to drop their items, if so, what chance?
mobs-drop-items-blue: true
mobs-drop-items-chance-blue: 3

#-----------Golden Moons---------------
#Sets the increment of golden moons
gold-moon-increment: 1
#Sets the chance of mobs dropping gold on death
mob-drop-gold-chance: 5
#Sets the chance of a mob spawning when you break a block
mob-spawn-on-block-break: 2
#Sets if mobs should drop items, if so, what chance?
mob-drop-items-blood: true
mob-drop-items-chance-gold: 2
#Sets if mobs are allowed to drop gold on death, if so what chance?
mobs-drop-gold: true
mobs-drop-gold-chance: 20
#Should players get mining effects? If so how strong? (Haste, night vision)
players-get-effects-gold: true
haste-level-gold: 1
night-vision-level-gold: 1

#-----------Water Moons----------------
#Sets the increment for water moons
water-moon-increment: 1
#Sets the chance of something special happening after a player catches a fish during Water Moon
fish-special-chance: 2
mob-drop-items-water: true
#Sets the chance of a drowned spawning if a special event occurs from the aforementioned event.
#An item will be given to a player if a Drowned is not spawned, so choose this carefully...
fish-drowned-chance: 20
#Should drowned get extra health? If so how much?
drowned-extra-health: true
#in half hearts
drowned-extra-health-value: 20


